##########################################################
#+------------------------------------------------------+#
#|                        Notes                         |#
#+------------------------------------------------------+#
##########################################################

# Gültige Colorcodes sind:
# &1, &2, &3, &4, &5, &6, &7, &8, &9
# &a, &b, &c, &d, &e, &f
# Gültige Format Codes sind:
# &n, &m, &l, &k

# Plugin By HappyBavarian07

# The permissions.yml file is only important for the plugin!!! so please don't change anything in there, otherwise part of the plugin might break.
# As soon as you delete a file, it will reset itself to the default with the next reload and will create itself again
# All Files are self updating, only the Language File Updater can be turned off. If you delete an Option or rename it, it will delete the other one (if exists) and take the Default Value

##########################################################
#+------------------------------------------------------+#
#|                       General                        |#
#+------------------------------------------------------+#
##########################################################

Plugin:
  # This is the prefix used by the plugin for chat messages
  # These messages can be edited in the language files
  Prefix: '&r[&4Admin&d-&8Panel&r] '

  # This is the System to sync Data across all to the Bungee Cord system connected Servers
  # Obivously it needs the Admin Panel Bungee Plugin to work
  # UNDER DEVELOPMENT
  # BungeeCord Part is not available online so this whole System will NOT work!
  BungeeSyncSystem:
    # here you can enable it
    enabled: false
    # Here you can change the Plugin Message Channel Names
    ChannelNames:
      In: "adminpanel:bungeein"
      Out: "adminpanel:bungeeout"
    # This Section is an Addition to the Bungee Cord system that has to be enabled in the Config of the Bungee Plugin aswell
    # This System uses Java Methods to establish a better connection between the Bungee Cord Server Admin Panel Plugin and the
    # Bukkit/Spigot/etc. Admin Panel Plugins.
    # The Setup is easy and you can find it here: <LinkToFAQ>
    JavaSockets:
      enabled: false
      # The public IP of the Bungee Server (localhost/0.0.0.0)
      hostName: 0.0.0.0
      # The Port in the Config of the Bungee Plugin
      port: 12345
      # The Name for the Server to register
      ClientName: "ExampleClientName"

  AddonSystem:
    # This Option disables/enables the Addon System for the Admin-Panel
    # A restart or reload of the Admin-Panel is required to start it!
    enabled: false

  # This is the language option you can add language files to the "languages" folder,
  # and then enter the name of the file (without .yml) here. Note upper and lower case!
  # Example: /plugins/Admin-Panel/languages/<Language>.yml | language (in the config): <Language>
  language: en

  # UNDER DEVELOPMENT
  # This is the language option for Updates you can, enter the name of the file (without .yml) here.
  # This Language will the Plugin use to update other Language Files
  # Note upper and lower case!
  # Example: /plugins/Admin-Panel/languages/<Language>.yml | languageForUpdates (in the config): Language
  languageForUpdates: en

  # This Option makes it that all Actions (Plugin Update, Admin Panel Open, ...) get logged
  # in the plugin.log File If You don't want this please disable this Option!
  LogActions: true

  # The Auto Admin-Panel Updater Section
  Updater:
    # If this is false the Plugin will no longer log if there is no update available.
    # This Option is for the normal Updater and for the Auto Plugin Updater.
    logNoUpdate: true
    # If this option is activated, the updater will automatically check for updates
    # The plugin uses https://spiget.org for this feature
    checkForUpdates: true
    # If this option is activated, the updater will automatically download the update (if available) from Spigot.
    # The update can then be found in plugins/Admin-Panel/downladed-update/Admin-Panel-<UpdateVersion>.jar!
    downloadPluginUpdate: false
    # If this option and the downloadPluginUpdate option is activated,
    # then the updater will automatically replace the plugin with the new version!
    automaticReplace: false
    # With this Option you can control how often the Updater should check!
    # You can configure here the Time between Checks (in Minutes)
    UpdateCheckTime: 5
    # This Option will enable/disable if the Plugin should automatically update the Language Files
    AutomaticLanguageFileUpdating: true

    # UNDER DEVELOPMENT
    # The Auto Plugin Updater Section (the Updater to update other Plugins automatically)
    PluginUpdater:
      # If this option is activated, the updater will automatically check for updates
      # If a Plugin has an Update it will download and replace it automatically, if enabled with the Options down below.
      # The plugin uses https://spiget.org for this feature
      enabled: false
      # If this option is activated, the updater will automatically download the update (if available) from Spigot.
      # The update can then be found in plugins/Admin-Panel/downladed-update/Admin-Panel-<UpdateVersion>.jar!
      downloadPluginUpdate: false
      # If this option and the downloadPluginUpdate option is activated,
      # then the updater will automatically replace the plugin with the new version!
      automaticReplace: false
      # Downloads and installs Plugins that are not installed on the Server but in the List
      downloadIfNotExists: false
      # This the Time in which the Updater will check the Plugins specified in data.yml
      # but only if checkForUpdatesFrequently is true
      checkForUpdatesFrequently: false
      UpdateCheckTime: 5
    # UNDER DEVELOPMENT

# These are the settings for the panel
Panel:

  # Here you can set whether there are sounds when opening an inventory of the plugin should be played
  PlaySoundsWhenOpened: true
  # This is the sound that is played when you open a panel / inventory
  # it is only played if the previous query is true
  SoundWhenOpened: ENTITY_BAT_TAKEOFF
  # That's the volume
  # Min: 0.0 Max: IDon'tNowtheLimit
  # Default: 100.0
  SoundVolume: 100.0
  # That's the pitch
  # Min: 0.0 Max: 2.0
  # Default: 1.0
  SoundPitch: 1.0

  # Here you can set whether an effect should be played when someone has a panel open
  # Of course only if you are not in the Vanish (not possible at the moment!)
  ShowEffectWhenOpened: true
  # Here you can set the effect
  EffectWhenOpened: ENDER_SIGNAL

##########################################################
#+------------------------------------------------------+#
#|                    Player Manager                    |#
#+------------------------------------------------------+#
##########################################################
# Pman = Player Manager
Pman:
  # This Features makes it so you can select yourself in the Player Manager
  # ! Use this at your own Risk !
  SelfSelect: false
  # Here you can set everything that can be set at Trolls
  Troll:
    # Here you can set how many entities are spawned when the Mob Dupe option is activated in the Troll menu
    # And the player kills an entity!
    # If you do too much, the game will likely lag
    MobDupe: 1
  Actions:
    # Here you can set how much life you get if someone opens up for you
    # click the Heal Item in the Actions menu in Pman
    # Max: 20.0 if you enter something higher, twenty units are taken from Spigot / Bukkit
    HealthHealAmount: 20.0
    # Here you can set how much hunger you get when someone opens up for you
    # click the Heal Item in the Actions menu in Pman
    # Max: 20 if you enter something higher, twenty units are taken from Spigot / Bukkit
    FoodLevelFillAmount: 20
    # Here you can set how long the player burns when you light it via the menu. Here it is calculated in seconds
    BurnDuration: 4

    # Here you can configure players who cannot be banned
    ExemptPlayers:
      - 'ExamplePlayer'

  Money:
    # This is the currency used for the money part in the Pman
    currency: $