##########################################################
#+------------------------------------------------------+#
#|                        Notes                         |#
#+------------------------------------------------------+#
##########################################################

# Gültige Colorcodes sind:
# &1, &2, &3, &4, &5, &6, &7, &8, &9
# &a, &b, &c, &d, &e, &f
# Gültige Format Codes sind:
# &n, &m, &l, &k

# Plugin By HappyBavarian07

# The Bans.yml file is only important for the plugin !!! so please don't change anything in there, otherwise part of the plugin might break.
# As soon as you delete a file, it will reset itself to the default with the next reload and will create itself again

##########################################################
#+------------------------------------------------------+#
#|                       General                        |#
#+------------------------------------------------------+#
##########################################################

Plugin:
  # This is the prefix used by the plugin in the console when starting or stopping
  StartPrefix: '&r[&4Admin&d-&8Panel&r]'
  # This is the prefix used by the plugin for chat messages
  # These messages can be edited in the messages.yml file
  Prefix: '&r[&4Admin&d-&8Panel&r]'

  # Currently Disabled
  ## If your server uses Supervanish then please enter the version here.This is important for identification because I cannot simply create a method for each individual version:)
  # SuperVanishVersion: 6.2.5

  # This is the language option you can add language files to the "languages" folder,
  # and then enter the name of the file (without .yml) here. Note upper and lower case!
  # Example: /plugins/Admin-Panel/languages/Language.yml | language (in the config): Language
  language: de
  Updater:
    # If this option is activated, the updater will automatically check for updates
    # (Attention: The updater will not recognize whether you have an old or a new version! Only differences in the version-name)
    # The plugin uses https://spiget.org for this feature
    checkForUpdates: true
    # If this option is activated, the updater will automatically download the update (if available) from Spigot.
    # The update can then be found in plugins/Admin-Panel/downladed-update/Admin-Panel-<UpdateVersion>.jar!
    downloadPluginUpdate: true
    # If this option and the downloadPluginUpdate option is activated,
    # then the updater will automatically replace the plugin with the new version!
    automaticReplace: false

# These are the settings for the panel
Panel:

  # Here you can set whether there are sounds when opening an inventory of the plugin should be played
  PlaySoundsWhenOpened: false
  # This is the sound that is played when you open a panel / inventory
  # it is only played if the previous query is true
  SoundWhenOpened: ENTITY_BAT_TAKEOFF
  # That's the volume
  # Min: 0.0 Max: IDon'tNowtheLimit
  # Default: 100.0
  SoundVolume: 100.0
  # That's the pitch
  # Min: 0.0 Max: 2.0
  # Default: 1.0
  SoundPitch: 1.0

  # Here you can set whether an effect should be played when someone has a panel open
  # Of course only if you are not in the Vanish (not possible at the moment!)
  ShowEffectWhenOpened: false
  # Here you can set the effect
  EffectWhenOpened: ENDER_SIGNAL

##########################################################
#+------------------------------------------------------+#
#|                    Player Manager                    |#
#+------------------------------------------------------+#
##########################################################
# Pman = Player Manager
Pman:
  # Here you can set everything that can be set at Trolls
  Troll:
    # Here you can set how many entities are spawned when the Mob Dupe option is activated in the Troll menu
    # And the player kills an entity!
    # If you do too much, the game will likely lag
    MobDupe: 1
  
  Actions:
    # Here you can set how much life you get if someone opens up for you
    # click the Heal Item in the Actions menu in Pman
    # Max: 20.0 if you enter something higher, twenty units are taken from Spigot / Bukkit
    HealthHealAmount: 20.0
    # Here you can set how much hunger you get when someone opens up for you
    # click the Heal Item in the Actions menu in Pman
    # Max: 20 if you enter something higher, twenty units are taken from Spigot / Bukkit
    FoodLevelFillAmount: 20
    # Here you can set how long the player burns when you light it via the menu. Here it is calculated in seconds
    BurnDuration: 4

    # Here you can configure players who cannot be banned
    ExemptPlayers:
      - 'ExamplePlayer'
    
  Money:
    # This is the currency used for the money part in the Pman
    currency: $

# Here you can set what you can spawn for mobs via the Player Manager in the Actions menu under Spawn Gui
# just set those you don't want to false
Spawn:
  Bat: true
  Bee: true
  Blaze: true
  Cat: true
  Cave_Spider: true
  Chicken: true
  Cod: true
  Cow: true
  Creeper: true
  Dolphin: true
  Donkey: true
  Drowned: true
  Elder_Guardian: true
  Enderman: true
  Endermite: true
  Evoker: true
  Fox: true
  Ghast: true
  Guardian: true
  Horse: true
  Husk: true
  Llama: true
  Magma_Cube: true
  Mooshroom: true
  Mule: true
  Ocelot: true
  Panda: true
  Parrot: true
  Phantom: true
  Pig: true
  Pillager: true
  Polar_Bear: true
  Pufferfish: true
  Rabbit: true
  Ravager: true
  Salmon: true
  Sheep: true
  Shulker: true
  Silverfish: true
  Skeleton: true
  Skeleton_Horse: true
  Slime: true
  Spider: true
  Squid: true
  Stray: true
  Tropical_Fish: true
  Turtle: true
  Vex: true
  Villager: true
  Vindicator: true
  Witch: true
  Wolf: true
  Zombie: true