name: Admin-Panel
main: de.happybavarian07.main.AdminPanelMain
version: ${project.version}
api-version: 1.13
author: HappyBavaraian07
depend: [PlaceholderAPI]
softdepend:
  - SuperVanish
  - Vault
load: POSTWORLD
loadbefore:
  - Vault
  - PlaceholderAPI
commands:
  adminpanel:
    description: Opens the Adminpanel
    usage: /adminpanel [<Player>]
    aliases: [apanel, adminp, ap]
  update:
    description: The Update Command
    usage: /update <Check|Download|ForceDownload|Replace|ForceReplace|GetLatest>

permissions:
  AdminPanel.*:
    default: op
    children:
      AdminPanel.SwitchLanguage: true
      AdminPanel.ReloadConfig: true
      AdminPanel.updatenotify: true
      AdminPanel.update: true
      AdminPanel.Bypass.*:
        default: op
        children:
          AdminPanel.Bypass.AffectedByPlayerManager:
            default: op
          AdminPanel.Bypass.KickInMainTenanceMode:
            default: op
          AdminPanel.Bypass.ChatMute:
            default: op
          AdminPanel.Bypass.KickAll:
            default: op
          AdminPanel.Bypass.ban:
            default: op
      AdminPanel.Button.*:
        default: op
        children:
          AdminPanel.Button.Close:
            default: op
          AdminPanel.Button.pageright:
            default: op
          AdminPanel.Button.pageleft:
            default: op
          AdminPanel.Button.refresh:
            default: op
      AdminPanel.open:
        default: op
      AdminPanel.open.other:
        default: op
      AdminPanel.PluginManager.*:
        default: op
        children:
          AdminPanel.PluginManager.open:
            default: op
          AdminPanel.PluginManager.InstallPlugins:
            default: op
          AdminPanel.PluginManager.LoadPlugins:
            default: op
          AdminPanel.PluginManager.PluginSettings.*:
            default: op
            children:
              AdminPanel.PluginManager.PluginSettings.Open:
                default: op
              AdminPanel.PluginManager.PluginSettings.Enable:
                default: op
              AdminPanel.PluginManager.PluginSettings.Disable:
                default: op
              AdminPanel.PluginManager.PluginSettings.Restart:
                default: op
              AdminPanel.PluginManager.PluginSettings.Unload:
                default: op
              AdminPanel.PluginManager.PluginSettings.Load:
                default: op
              AdminPanel.PluginManager.PluginSettings.Permissions:
                default: op
              AdminPanel.PluginManager.PluginSettings.Commands:
                default: op
      AdminPanel.ServerStop:
        default: op
      AdminPanel.ServerRestart:
        default: op
      AdminPanel.WorldManagment.*:
        default: op
        children:
          AdminPanel.WorldManagment.Open:
            default: op
          AdminPanel.WorldManagment.Gamerules:
            default: op
          AdminPanel.WorldManagment.PVP:
            default: op
          AdminPanel.WorldManagment.Time:
            default: op
          AdminPanel.WorldManagment.Weather:
            default: op
          AdminPanel.WorldManagment.Settings:
            default: op
          AdminPanel.WorldManagment.Create:
            default: op
      AdminPanel.ServerManagment.*:
        default: op
        children:
          AdminPanel.ServerManagment.KickAllPlayers:
            default: op
          AdminPanel.ServerManagment.Whitelist:
            default: op
          AdminPanel.ServerManagment.Broadcast:
            default: op
          AdminPanel.ServerManagment.MaintenanceMode:
            default: op
          AdminPanel.ServerManagment.ChatManager.*:
            default: op
            children:
              AdminPanel.ServerManagment.ChatManager.Clear:
                default: op
              AdminPanel.ServerManagment.ChatManager.Open:
                default: op
              AdminPanel.ServerManagment.ChatManager.Mute:
                default: op
          AdminPanel.ServerManagment.Open:
            default: op
          AdminPanel.ServerManagment.ManageWhitelist:
            default: op
      AdminPanel.PlayerManager.*:
        default: op
        children:
          AdminPanel.PlayerManager.open:
            default: op
          AdminPanel.PlayerManager.BannedPlayers:
            default: op
          AdminPanel.PlayerManager.PlayerSettings.*:
            default: op
            children:
              AdminPanel.PlayerManager.PlayerSettings.Open:
                default: op
              AdminPanel.PlayerManager.PlayerSettings.Ban:
                default: op
              AdminPanel.PlayerManager.PlayerSettings.Unban:
                default: op
              AdminPanel.PlayerManager.PlayerSettings.Kick:
                default: op
              AdminPanel.PlayerManager.PlayerSettings.Permissions:
                default: op
                children:
                  AdminPanel.PlayerManager.PlayerSettings.Permissions.Add: true
                  AdminPanel.PlayerManager.PlayerSettings.Permissions.Info: true
                  AdminPanel.PlayerManager.PlayerSettings.Permissions.List: true
                  AdminPanel.PlayerManager.PlayerSettings.Permissions.Remove: true
                  AdminPanel.PlayerManager.PlayerSettings.Permissions.Open: true
              AdminPanel.PlayerManager.PlayerSettings.OpenMenu.Ban:
                default: op
              AdminPanel.PlayerManager.PlayerSettings.OpenMenu.Kick:
                default: op
              AdminPanel.PlayerManager.PlayerSettings.OpenMenu.Actions:
                default: op
              AdminPanel.PlayerManager.PlayerSettings.OpenMenu.Money:
                default: op
              AdminPanel.PlayerManager.PlayerSettings.Actions.Inventoryview:
                default: op
              AdminPanel.PlayerManager.PlayerSettings.Money.Give:
                default: op
              Adminpanel.PlayerManager.PlayerSettings.Money.Set:
                default: op
              AdminPanel.PlayerManager.PlayerSettings.Money.Take:
                default: op
              AdminPanel.PlayerManager.PlayerSettings.Actions.*:
                default: op
                children:
                  AdminPanel.PlayerManager.PlayerSettings.Actions.Burn:
                    default: op
                  AdminPanel.PlayerManager.PlayerSettings.Actions.Vanish:
                    default: op
                  AdminPanel.PlayerManager.PlayerSettings.Actions.Troll.*:
                    default: op
                    children:
                      AdminPanel.PlayerManager.PlayerSettings.Actions.Troll.Open: true
                      AdminPanel.PlayerManager.PlayerSettings.Actions.Troll.FakeOp: true
                      AdminPanel.PlayerManager.PlayerSettings.Actions.Troll.FakeDeop: true
                      AdminPanel.PlayerManager.PlayerSettings.Actions.Troll.FakeTNT: true
                      AdminPanel.PlayerManager.PlayerSettings.Actions.Troll.BuildPrevent: true
                      AdminPanel.PlayerManager.PlayerSettings.Actions.Troll.DropPlayersInv: true
                      AdminPanel.PlayerManager.PlayerSettings.Actions.Troll.VillagerSounds: true
                      AdminPanel.PlayerManager.PlayerSettings.Actions.Troll.MuteChat: true
                      AdminPanel.PlayerManager.PlayerSettings.Actions.Troll.HurtingWater: true
                      AdminPanel.PlayerManager.PlayerSettings.Actions.Troll.DupeMobs: true
                      AdminPanel.PlayerManager.PlayerSettings.Actions.Troll.KickForWhitelist: true
                      AdminPanel.PlayerManager.PlayerSettings.Actions.Troll.KickForServerstop: true
                      AdminPanel.PlayerManager.PlayerSettings.Actions.Troll.KickForError: true
                      AdminPanel.PlayerManager.PlayerSettings.Actions.Troll.KickForConnectionReset: true
                  AdminPanel.PlayerManager.PlayerSettings.Actions.Potions:
                    default: op
                  AdminPanel.PlayerManager.PlayerSettings.Actions.Ban:
                    default: op
                  AdminPanel.PlayerManager.PlayerSettings.Actions.Unban:
                    default: op
                  AdminPanel.PlayerManager.PlayerSettings.Actions.Kick:
                    default: op
                  AdminPanel.PlayerManager.PlayerSettings.Actions.Gamemode:
                    default: op
                  AdminPanel.PlayerManager.PlayerSettings.Actions.Spawner:
                    default: op
                  AdminPanel.PlayerManager.PlayerSettings.Actions.Heal:
                    default: op
                  AdminPanel.PlayerManager.PlayerSettings.Actions.Feed:
                    default: op
                  AdminPanel.PlayerManager.PlayerSettings.Actions.Kill:
                    default: op
                  AdminPanel.PlayerManager.PlayerSettings.Actions.TeleportYouToPlayer:
                    default: op
                  AdminPanel.PlayerManager.PlayerSettings.Actions.TeleportPlayerToYou:
                    default: op
                  AdminPanel.PlayerManager.PlayerSettings.Actions.Op:
                    default: op
                  AdminPanel.PlayerManager.PlayerSettings.Actions.Deop:
                    default: op
                  AdminPanel.PlayerManager.PlayerSettings.Actions.PlayerSpawnLocation:
                    default: op