name: Admin-Panel
main: de.happybavarian07.main.Main
version: 1.0
api-version: 1.13
author: HappyBavaraian07
depend: [Vault]
softdepend: [Vault]
load: POSTWORLD
commands:
  adminpanel:
    description: Opens the Adminpanel
    usage: /adminpanel [<Player>]
    aliases: [apanel, Adminp, ap]

permissions:
  AdminPanel.*:
    default: op
    description: Gibt dir Zugriff auf Alle Admin Panel Commands
    children:
      AdminPanel.Bypass.*:
        default: op
        description: Gibt dir Zugriff alle Bypasses zu nutzen
        children:
          AdminPanel.Bypass.AffectedByPlayerManager:
            default: op
            description: Du bist nicht mehr von den Aktionen des Player Managers betroffen
          AdminPanel.Bypass.KickInMainTenanceMode:
            default: op
            description: Du bist nicht mehr von den Aktionen des Player Managers betroffen
          AdminPanel.Bypass.ChatMute:
            default: op
            description: Du bist nicht mehr von den Aktionen des Player Managers betroffen
      AdminPanel.Button.*:
        default: op
        description: Gibt dir Zugriff auf alle Buttons in allen Paneln
        children:
          AdminPanel.Button.Refresh:
            default: op
            description: Gibt dir Zugriff auf den Refresh Button
          AdminPanel.Button.Close:
            default: op
            description: Gibt dir Zugriff auf den Close Button
          AdminPanel.Button.Back:
            default: op
            description: Gibt dir Zugriff auf den Back Button
      AdminPanel.open:
        default: op
        description: Gibt dir Zugriff auf den Befehl um das Panel zu oeffnen
      AdminPanel.open.other:
        default: op
        description: Gibt dir Zugriff auf den Befehl um das Panel zu oeffnen
      AdminPanel.PluginManager.*:
        default: op
        description: Gibt dir Zugriff auf alle PluginManager Panel Befehle
        children:
          AdminPanel.PluginManager.open:
            default: op
            description: Gibt dir Zugriff auf das Item fuer den PluginManager klicken
          AdminPanel.PluginManager.PluginSettings.*:
            default: op
            description: Gibt dir Zugriff auf alle Plugin Settings
            children:
              AdminPanel.PluginManager.PluginSettings.Open:
                default: op
                description: Gibt dir Zugriff auf das Item fuer ein plugin zu klicken
              AdminPanel.PluginManager.PluginSettings.Enable:
                default: op
                description: Gibt dir Zugriff auf das Item zum enablen des Plugins das du ausgewaehlt hast zu klicken
              AdminPanel.PluginManager.PluginSettings.Disable:
                default: op
                description: Gibt dir Zugriff auf das Item zum disablen des Plugins das du ausgewaehlt hast zu klicken
              AdminPanel.PluginManager.PluginSettings.Restart:
                default: op
                description: Gibt dir Zugriff auf das Item zum restarten des Plugins das du ausgewaehlt hast zu klicken
              AdminPanel.PluginManager.PluginSettings.Permissions:
                default: op
                description: Gibt dir Zugriff auf das Item zum auflisten der Permissions des Plugins das du ausgewaehlt hast zu klicken
              AdminPanel.PluginManager.PluginSettings.Commands:
                default: op
                description: Gibt dir Zugriff auf das Item zum auflisten der Commands des Plugins das du ausgewaehlt hast zu klicken
      AdminPanel.ServerStop:
        default: op
        description: Gibt dir Zugriff auf das Item zum Server stoppen zu klicken
      AdminPanel.ServerReload:
        default: op
        description: Gibt dir Zugriff auf das Item zum Server reloaden zu klicken
      AdminPanel.WorldManagment.*:
        default: op
        description: Gibt dir Zugriff auf alle World Managment Sachen
        children:
          AdminPanel.WorldManagment.Open:
            default: op
            description: Gibt dir Zugriff den World Manager zu oeffnen
          AdminPanel.WorldManagment.Gamerules:
            default: op
            description: Gibt dir Zugriff den World Manager zu oeffnen
          AdminPanel.WorldManagment.PVP:
            default: op
            description: Gibt dir Zugriff den World Manager zu oeffnen
          AdminPanel.WorldManagment.Time_Weather.Open:
            default: op
            description: Gibt dir Zugriff den World Manager zu oeffnen
          AdminPanel.WorldManagment.Time.Change:
            default: op
            description: Gibt dir Zugriff die Zeit umzustellen
          AdminPanel.WorldManagment.Weather.Change:
            default: op
            description: Gibt dir Zugriff das Wetter umzustellen
      AdminPanel.ServerManagment.*:
        default: op
        description: Gibt dir Zugriff auf alle Server Managment Sachen
        children:
          AdminPanel.ServerManagment.KickAllPlayers:
            default: op
            description: Gibt dir Zugriff alle Spieler auf deinem Server zu kicken
          AdminPanel.ServerManagment.MaintenanceMode:
            default: op
            description: Gibt dir Zugriff alle Spieler auf deinem Server zu kicken
          AdminPanel.ServerManagment.ChatManager.*:
            default: op
            description: Gibt dir Zugriff alle Spieler auf deinem Server zu kicken
            children:
              AdminPanel.ServerManagment.ChatManager.Clear:
                default: op
                description: Gibt dir Zugriff ueber den Manager den Chat zu clearen
              AdminPanel.ServerManagment.ChatManager.Open:
                default: op
                description: Gibt dir Zugriff ueber den Manager den Chat zu clearen
              AdminPanel.ServerManagment.ChatManager.Mute:
                default: op
                description: Gibt dir Zugriff ueber den Manager den Chat zu muten und zu unmuten
          AdminPanel.ServerManagment.Open:
            default: op
            description: Gibt dir Zugriff alle Spieler auf deinem Server zu kicken
      AdminPanel.PlayerManager.*:
        default: op
        description: Gibt dir Zugriff auf alle Player Manager Panel Befehle
        children:
          AdminPanel.PlayerManager.open:
            default: op
            description: Gibt dir Zugriff auf das Item fuer den Player Manager Panel klicken
          AdminPanel.PlayerManager.PlayerSettings.*:
            default: op
            description: Gibt dir Zugriff auf alle Playersettings
            children:
              AdminPanel.PlayerManager.Ban.Ban:
                default: op
                description: Gibt dir Zugriff den Spieler ueber das Menu zu perma bannen
              AdminPanel.PlayerManager.Ban.Unban:
                default: op
                description: Gibt dir Zugriff den Spieler ueber das Menu zu perma bannen
              AdminPanel.PlayerManager.Kick.Kick:
                default: op
                description: Gibt dir Zugriff den Spieler ueber das Menu zu kicken
              AdminPanel.PlayerManager.OpenMenu.Ban:
                default: op
                description: Gibt dir Zugriff auf das Item fuer das Ban Menu in den Player Settings
              AdminPanel.PlayerManager.OpenMenu.Kick:
                default: op
                description: Gibt dir Zugriff auf das Item fuer das Ban Menu in den Player Settings
              AdminPanel.PlayerManager.OpenMenu.Actions:
                default: op
                description: Gibt dir Zugriff auf das Item fuer die Actions in den Player Settings
              AdminPanel.PlayerManager.OpenMenu.Money:
                default: op
                description: Gibt dir Zugriff auf das Item fuer das Geld in den Player Settings
              AdminPanel.PlayerManager.Actions.Inventoryview:
                default: op
                description: Gibt dir Zugriff auf das Item zum einsehen des Inventars des Spielers zu klicken
              AdminPanel.PlayerManager.Money.Give:
                default: op
                description: Gibt dir Zugriff dem Spieler Geld zu geben (Vault + Economy)
              Adminpanel.PlayerManager.Money.Set:
                default: op
                description: Gibt dir Zugriff dem Spieler Geld zu setzen (Vault + Economy)
              AdminPanel.PlayerManager.Money.Take:
                default: op
                description: Gibt dir Zugriff dem Spieler Geld weg zu nehmen (Vault + Economy)
              AdminPanel.PlayerManager.Actions.*:
                default: op
                description: Gibt dir Zugriff auf alle Aktionen
                children:
                  AdminPanel.PlayerManager.Actions.Burn:
                    default: op
                    description: Gibt dir Zugriff auf die Potions
                  AdminPanel.PlayerManager.Actions.Potions:
                    default: op
                    description: Gibt dir Zugriff auf die Potions
                  AdminPanel.PlayerManager.Actions.Open:
                    default: op
                    description: Gibt dir Zugriff auf das Item fuer die Player Settings
                  AdminPanel.PlayerManager.Actions.Ban:
                    default: op
                    description: Gibt Zugriff einen Spieler ueber den Manager zu bannen
                  AdminPanel.PlayerManager.Actions.Unban:
                    default: op
                    description: Gibt Zugriff einen Spieler ueber den Manager zu entbannen
                  AdminPanel.PlayerManager.Actions.Kick:
                    default: op
                    description: Gibt Zugriff einen Spieler ueber den Manager zu kicken
                  AdminPanel.PlayerManager.Actions.Gamemode:
                    default: op
                    description: Gibt Zugriff einem Spieler ueber den Manager den Gamemode zu wechseln
                  AdminPanel.PlayerManager.Actions.Spawner:
                    default: op
                    description: Gibt Zugriff Entitaeten beim Spieler zu erzeugen
                  AdminPanel.PlayerManager.Actions.Heal:
                    default: op
                    description: Gibt Zugriff den Spieler zu heilen
                  AdminPanel.PlayerManager.Actions.Feed:
                    default: op
                    description: Gibt Zugriff Das Food Level des Spieler aufzufuellen
                  AdminPanel.PlayerManager.Actions.Kill:
                    default: op
                    description: Gibt Zugriff den Spieler zu killen
                  AdminPanel.PlayerManager.Actions.TeleportYouToPlayer:
                    default: op
                    description: Gibt Zugriff den Spieler zu killen
                  AdminPanel.PlayerManager.Actions.TeleportPlayerToYou:
                    default: op
                    description: Gibt Zugriff den Spieler zu killen