package de.happybavarian07.adminpanel.languageold.expressionparser;

import de.happybavarian07.coolstufflib.languagemanager.expressionengine.*;
import de.happybavarian07.coolstufflib.languagemanager.expressionengine.interfaces.MaterialCondition;
import org.bukkit.Material;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

public class LanguageFunctionManagerTest {
    private ExpressionEngine parser;
    private LanguageFunctionManager functionManager;

    @BeforeEach
    void setUp() {
        parser = new ExpressionEngine();
        functionManager = parser.getFunctionManager();
    }

    @Test
    void testRegisterAndEvaluateSimpleFunction() {
        functionManager.registerFunction("add<double>(a, b) => a + b");
        Object result = parser.evaluate("add(2, 3)");
        Assertions.assertEquals(5.0, result); // Assuming double arithmetic
        // with the default number type
        functionManager.unregisterFunction("add");
        functionManager.registerFunction("add<int>(a, b) => a + b");
        result = parser.evaluate("add(5, 3)");
        Assertions.assertEquals(8, result); // Assuming int arithmetic
    }

    @Test
    void testInvalidFunctionFormatMissingArrow() {
        Assertions.assertThrows(IllegalArgumentException.class, () -> {
            functionManager.registerFunction("add(a, b) a + b");
        });
    }

    @Test
    void testInvalidFunctionFormatMismatchedParentheses() {
        Assertions.assertThrows(IllegalArgumentException.class, () -> {
            functionManager.registerFunction("add(a, b => a + b");
        });
        Assertions.assertThrows(IllegalArgumentException.class, () -> {
            functionManager.registerFunction("add(a, b)) => a + b");
        });
    }

    @Test
    void testArgumentCountMismatch() {
        functionManager.registerFunction("add(a, b) => a + b");
        Assertions.assertThrows(RuntimeException.class, () -> {
            parser.evaluate("add(1)");
        });
    }

    @Test
    void testArgumentTypeMismatch() {
        functionManager.registerFunction("add(a, b) => a + b");
        Assertions.assertThrows(RuntimeException.class, () -> {
            parser.evaluate("add(1, 'str')");
        });
    }

    @Test
    void testIfElifElseMaterialCondition() {
        parser.getInterpreter().setVariable("x", 4);
        String expr = """
                if x > 3: Out<Material>(STONE)
                elif x == 2: Out<Material>(GLASS)
                elif x < 0: Out<Material>(DIRT)
                else: Out<Material>(BARRIER)""";
        // Debug: print all tokens generated by the lexer for this input
        Lexer lexer = new Lexer(expr);
        java.util.List<Token> tokens = lexer.scanTokens();
        StringBuilder sb = new StringBuilder();
        sb.append("Tokens:\n");
        for (Token t : tokens) {
            if (t.type() == TokenType.NEWLINE) continue;
            sb.append(t.lexeme()).append(" ");
        }
        System.out.println(sb);
        MaterialCondition cond = parser.parse(expr, Material.BARRIER);
        Assertions.assertEquals(Material.STONE, cond.getMaterial());

        parser.getInterpreter().setVariable("x", 2);
        cond = parser.parse(expr, Material.BARRIER);
        Assertions.assertEquals(Material.GLASS, cond.getMaterial());

        parser.getInterpreter().setVariable("x", -5);
        System.out.println("\n--- Testing with x = -5 ---");
        System.out.println("Variable x = " + parser.getInterpreter().getVariable("x"));
        cond = parser.parse(expr, Material.BARRIER);
        System.out.println("Result material: " + cond.getMaterial());
        Assertions.assertEquals(Material.DIRT, cond.getMaterial());

        parser.getInterpreter().setVariable("x", 0);
        cond = parser.parse(expr, Material.BARRIER);
        Assertions.assertEquals(Material.BARRIER, cond.getMaterial());
    }
}
